name: mama
description: >
  Starter app

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: ^0.19.0

  # Stream
  rxdart: ^0.28.0

  # -- service locator -- #
  provider: ^6.1.2

  # -- state manager -- #
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # -- codegen -- #
  json_annotation: ^4.8.1

  # -- networking -- #
  dio: ^5.3.3

  # Persisting
  drift: ^2.13.1
  sqlite3: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  sqlite3_flutter_libs: ^0.5.18

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: ^8.9.0
  logging: ^1.2.0

  # Utils
  platform_info: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.1.0
  mocktail: ^1.0.1
  reactive_forms: ^17.0.1
  json_serializable: ^6.8.0

  icons_launcher: ^3.0.0

  # -- navigation -- #
  go_router: ^14.2.7

  # -- localization -- #
  flutter_localizations:
    sdk: flutter
  slang: ^3.31.2
  slang_flutter: ^3.31.0

  # -- ui -- #
  flex_color_scheme: ^7.3.1
  tab_container: ^3.5.3
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  pin_code_fields: ^8.0.1
  flutter_toggle_button: ^0.0.3
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  google_fonts: ^6.2.1
  reactive_date_time_picker: ^4.0.0
  flutter_envify: ^3.0.1
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  syncfusion_flutter_charts: ^27.1.50

dev_dependencies:
  # -- testing -- #
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # -- utils -- #
  flutter_gen_runner: ^5.3.2
  flutter_native_splash: ^2.3.5

  # -- codegen -- #
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.0+1
  slang_build_runner: ^3.31.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Medium.ttf
        - asset: assets/fonts/SFProText-Bold.ttf


flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
      
 