version: "3"

tasks:
  flutter:get:
    desc: Get flutter dependencies
    summary: |
      Get flutter dependencies
    cmds:
      - flutter pub get

  dart:gen:
    desc: Generate dart files
    summary: |
      Run codegen
    cmds:
      - dart run build_runner build --delete-conflicting-outputs

  dart:gen:watch:
    desc: Generate dart files
    summary: |
      Watch codegen
    cmds:
      - dart run build_runner watch --delete-conflicting-outputs

  # mama-related, safe to be removed for production
  tmpl:init:
    desc: Initialize mama for development
    summary: |
      Initialize mama for development.
      Safe to be deleted for production.
    deps:
      - tmpl:git:config
    cmds:
      - flutter create .

  tmpl:git:config:
    desc: Configure git for mama development
    summary: |
      Configure git for mama development. 
      Safe to be deleted for production.
    cmds:
      - git config core.excludesfile .gitignore-dev
  # mama-related, safe to be removed for production
